// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Idempotency struct {
	UserID     uuid.UUID
	Key        string
	MethodPath string
	Request    []byte
	Response   []byte
}

type Pet struct {
	RowID       int32
	ID          uuid.UUID
	Name        string
	DateOfBirth time.Time
}
