name: go test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine3.17
        env:
          POSTGRES_PASSWORD: bestpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3
    - name: Test
      run: POSTGRES_USER=postgres POSTGRES_PASS=bestpassword POSTGRES_HOST=127.0.0.1:5432 go test -race -v ./...
