name: go test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine3.17
        env:
          POSTGRES_PASSWORD: bestpassword

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3

    - name: Test
      run: POSTGRES_USER=postgres POSTGRES_PASS=bestpassword POSTGRES_HOST=postgres go test -race -v ./...
